aliases: []
creation_timestamp: 1729767836106
current_stage: None
description: null
last_updated_timestamp: 1729767836106
name: Abalone Model
run_id: f20b203f6e3c4b278a4374b20a8af9e5
run_link: null
source: file:///c:/Users/charl/OneDrive/Documents/ml_ops/final_project/xhec-mlops-project-student/notebooks/mlruns/585163062762099395/f20b203f6e3c4b278a4374b20a8af9e5/artifacts/model
status: READY
status_message: null
storage_location: file:///c:/Users/charl/OneDrive/Documents/ml_ops/final_project/xhec-mlops-project-student/notebooks/mlruns/585163062762099395/f20b203f6e3c4b278a4374b20a8af9e5/artifacts/model
user_id: null
version: 1
