name: CI

on: [push, pull_request]

jobs:
  CI:
    name: Launching CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pip-tools and pip-compile requirements
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools
          pip-compile requirements.in
          pip-compile requirements-dev.in

      - name: Install dependencies from requirements.txt
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run Pre-commit hooks (formatting, linting & tests)
        run: pre-commit run --all-files --show-diff-on-failure